
-- Maak de tabellen aan
CREATE TABLE leerlingen (
    id INT PRIMARY KEY,
    voornaam VARCHAR(50),
    achternaam VARCHAR(50),
    email VARCHAR(100),
    klas VARCHAR(10)
);

CREATE TABLE bedrijven (
    id INT PRIMARY KEY,
    naam VARCHAR(100),
    adres VARCHAR(150),
    email VARCHAR(100),
    sector VARCHAR(50)
);

-- Voeg leerlingen toe
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (1, 'Tom', 'Frerichs', 'tom.frerichs1@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (2, 'Maya', 'van Emmelen', 'maya.van emmelen2@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (3, 'Lukas', 'Lage', 'lukas.lage3@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (4, 'Esther', 'Mathurin', 'esther.mathurin4@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (5, 'Sven', 'Neuteboom', 'sven.neuteboom5@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (6, 'Amira', 'de Werd', 'amira.de werd6@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (7, 'Nora', 'Postma', 'nora.postma7@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (8, 'Puck', 'Slaetsdochter', 'puck.slaetsdochter8@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (9, 'Maria', 'van den Eerenbeemt', 'maria.van den eerenbeemt9@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (10, 'Charlotte', 'le Floch', 'charlotte.le floch10@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (11, 'Leon', 'van de Wal', 'leon.van de wal11@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (12, 'Sophia', 'Aeije', 'sophia.aeije12@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (13, 'Sven', 'de Marduras', 'sven.de marduras13@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (14, 'Jayson', 'Bloemendaal', 'jayson.bloemendaal14@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (15, 'Esmee', 'van der Linden', 'esmee.van der linden15@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (16, 'Beau', 'Robbrechts Bruijne', 'beau.robbrechts bruijne16@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (17, 'Julia', 'Speijer', 'julia.speijer17@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (18, 'Michelle', 'Heyne', 'michelle.heyne18@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (19, 'Julia', 'van het Heerenveen', 'julia.van het heerenveen19@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (20, 'Vigo', 'van de Klashorst', 'vigo.van de klashorst20@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (21, 'Jennifer', 'de Vries', 'jennifer.de vries21@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (22, 'Roos', 'Hekker', 'roos.hekker22@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (23, 'Hailey', 'de Graaf', 'hailey.de graaf23@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (24, 'Sam', 'Roose', 'sam.roose24@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (25, 'Pleun', 'Bresse', 'pleun.bresse25@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (26, 'Raf', 'Dennenberg', 'raf.dennenberg26@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (27, 'Romy', 'le Briel', 'romy.le briel27@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (28, 'Zoë', 'Werdes', 'zoë.werdes28@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (29, 'Emir', 'Bastiaanse', 'emir.bastiaanse29@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (30, 'Pim', 'van Venrooy', 'pim.van venrooy30@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (31, 'Mila', 'Lensen', 'mila.lensen31@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (32, 'Sophia', 'Stettyn', 'sophia.stettyn32@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (33, 'Luna', 'Huijs', 'luna.huijs33@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (34, 'Imran', 'Middelkoop', 'imran.middelkoop34@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (35, 'Noor', 'Hendriks', 'noor.hendriks35@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (36, 'Florian', 'Pieters', 'florian.pieters36@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (37, 'Isabel', 'Kuipers', 'isabel.kuipers37@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (38, 'Guus', 'Koret', 'guus.koret38@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (39, 'Esmee', 'Mathieu', 'esmee.mathieu39@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (40, 'Tijs', 'Scardino', 'tijs.scardino40@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (41, 'Selena', 'van Stralen', 'selena.van stralen41@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (42, 'Jorn', 'Schotte', 'jorn.schotte42@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (43, 'Kevin', 'van den Eerenbeemt', 'kevin.van den eerenbeemt43@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (44, 'Amelia', 'Muller', 'amelia.muller44@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (45, 'Joey', 'Verhagen', 'joey.verhagen45@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (46, 'Daniel', 'de Jager', 'daniel.de jager46@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (47, 'Lise', 'Versluijs', 'lise.versluijs47@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (48, 'Annemijn', 'Klein', 'annemijn.klein48@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (49, 'Ivan', 'Lensen', 'ivan.lensen49@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (50, 'Annemijn', 'van den Brand', 'annemijn.van den brand50@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (51, 'Nadia', 'Walter', 'nadia.walter51@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (52, 'Rowan', 'Dachgeldt', 'rowan.dachgeldt52@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (53, 'Sanne', 'Verhoeven', 'sanne.verhoeven53@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (54, 'Nora', 'Keijzer', 'nora.keijzer54@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (55, 'Elias', 'van Landen', 'elias.van landen55@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (56, 'Silke', 'Lijn', 'silke.lijn56@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (57, 'Noor', 'Spies', 'noor.spies57@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (58, 'Thijs', 'Hoppenbrouwer', 'thijs.hoppenbrouwer58@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (59, 'Niek', 'Versluijs', 'niek.versluijs59@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (60, 'Helena', 'Kisman', 'helena.kisman60@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (61, 'Féline', 'Vermeulen', 'féline.vermeulen61@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (62, 'Ravi', 'Cornelisse', 'ravi.cornelisse62@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (63, 'Cato', 'Weeldenburg', 'cato.weeldenburg63@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (64, 'Duuk', 'Laffray', 'duuk.laffray64@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (65, 'Livia', 'de Gruijter', 'livia.de gruijter65@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (66, 'Arthur', 'Hemma van Allemanië', 'arthur.hemma van allemanië66@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (67, 'Aya', 'Pauwels', 'aya.pauwels67@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (68, 'Liza', 'Kallen', 'liza.kallen68@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (69, 'Noa', 'van Suinvorde', 'noa.van suinvorde69@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (70, 'Catharina', 'van den Oever', 'catharina.van den oever70@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (71, 'Sylvie', 'Hemma van Allemanië', 'sylvie.hemma van allemanië71@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (72, 'Alyssa', 'Unruoch Hunerik', 'alyssa.unruoch hunerik72@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (73, 'Willem', 'Knoers', 'willem.knoers73@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (74, 'Ilse', 'Lamotte', 'ilse.lamotte74@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (75, 'Jorn', 'van Dam', 'jorn.van dam75@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (76, 'Casper', 'Jerusalem', 'casper.jerusalem76@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (77, 'Aya', 'van Vlaanderen', 'aya.van vlaanderen77@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (78, 'Ivan', 'van den Brink', 'ivan.van den brink78@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (79, 'Sofia', 'van Straaten', 'sofia.van straaten79@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (80, 'Jamie', 'Blewanus', 'jamie.blewanus80@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (81, 'Adam', 'Drysdale', 'adam.drysdale81@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (82, 'Naomi', 'de Hoog', 'naomi.de hoog82@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (83, 'Leah', 'Stichter', 'leah.stichter83@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (84, 'Lorenzo', 'Belpere', 'lorenzo.belpere84@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (85, 'Bryan', 'van Gelder', 'bryan.van gelder85@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (86, 'Noëlle', 'Soos', 'noëlle.soos86@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (87, 'Fiene', 'Everde', 'fiene.everde87@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (88, 'Quinn', 'Sire', 'quinn.sire88@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (89, 'Dina', 'van den Nuwenhijsen', 'dina.van den nuwenhijsen89@example.com', '6B');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (90, 'Jari', 'Schulten', 'jari.schulten90@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (91, 'Mads', 'Hendrikse', 'mads.hendrikse91@example.com', '6A');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (92, 'Benjamin', 'Kas', 'benjamin.kas92@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (93, 'Joshua', 'Bosman', 'joshua.bosman93@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (94, 'Lauren', 'van Dongen', 'lauren.van dongen94@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (95, 'Amy', 'Post', 'amy.post95@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (96, 'Lina', 'Frankhuizen', 'lina.frankhuizen96@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (97, 'Sten', 'Henric van den Nuwenhuse', 'sten.henric van den nuwenhuse97@example.com', '6D');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (98, 'Merel', 'van Herstal', 'merel.van herstal98@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (99, 'Lukas', 'van Goerle', 'lukas.van goerle99@example.com', '6C');
INSERT INTO leerlingen (id, voornaam, achternaam, email, klas) VALUES (100, 'Brian', 'Waardeloo', 'brian.waardeloo100@example.com', '6B');

-- Voeg bedrijven toe
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (1, 'Royal Spiker', 'Isabellasingel 42, 4722BN, Huissen', 'info1@royalspiker.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (2, 'Sulzer', 'Seppad 26, 3410 EM, Tytsjerk', 'info2@sulzer.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (3, 'Friehus BV', 'Zoeyboulevard 9, 1308TK, Lithoijen', 'info3@friehusbv.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (4, 'Intergamma', 'Laralaan 76, 7805UH, It Heidenskip', 'info4@intergamma.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (5, 'Cisco', 'Nisasingel 720, 8068 VF, Zwartewaal', 'info5@cisco.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (6, 'Goedhart Groep', 'Norahsingel 6, 7205CO, Wormerveer', 'info6@goedhartgroep.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (7, 'ASN', 'Esmeepad 8, 9584TQ, Zevenaar', 'info7@asn.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (8, 'Tech Data Nederland', 'Lisaweg 27, 9286 WC, Arcen', 'info8@techdatanederland.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (9, 'Chrodtrud & Moensendijk', 'Nadinepad 528, 8190EE, Soerendonk', 'info9@chrodtrud&moensendijk.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (10, 'Greenchoice', 'Jellestraat 4, 9948RV, Deursen-Dennenburg', 'info10@greenchoice.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (11, 'Royal van den Nuwenhuysen', 'Lucydreef 4, 1169 DK, Bitgum', 'info11@royalvandennuwenhuysen.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (12, 'Heyne NV', 'Elizabethsteeg 062, 3229 YV, Nij Altoenae', 'info12@heynenv.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (13, 'Brouwer & Reimes', 'Kaylaan 2, 9527OC, Breedenbroek', 'info13@brouwer&reimes.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (14, 'Stichting Uittenbosch', 'Silsingel 4, 5600QX, Boxtel', 'info14@stichtinguittenbosch.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (15, 'Koninklijke Mallien', 'Bjornring 28, 1168YM, Dokkum', 'info15@koninklijkemallien.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (16, 'Suijker NV', 'Juulsingel 268, 4205 IZ, Naaldwijk', 'info16@suijkernv.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (17, 'Koninklijke Kamper', 'Catoweg 7, 6026 DT, Voorhout', 'info17@koninklijkekamper.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (18, 'van Luxemburg Groep', 'Tomsteeg 2, 7118TZ, Katlijk', 'info18@vanluxemburggroep.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (19, 'Royal die Witte', 'Sepstraat 1, 4716TG, Velsen-Zuid', 'info19@royaldiewitte.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (20, 'Brisee & Claesner', 'Vigosingel 3, 8810AN, Bosschenhoofd', 'info20@brisee&claesner.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (21, 'SBM Offshore', 'Elisabethboulevard 84, 2051 LW, Snikzwaag', 'info21@sbmoffshore.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (22, 'Bloemendaal & Höning', 'Alyssaweg 019, 6968 KC, Hoogersmilde', 'info22@bloemendaal&höning.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (23, 'IMC Trading', 'Loïsboulevard 6, 8169 OJ, Sint-Annaland', 'info23@imctrading.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (24, 'Royal Hellevoort', 'Larslaan 5, 9308 VK, Delfgauw', 'info24@royalhellevoort.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (25, 'Warner Bros/Eyeworks', 'Fayehof 646, 2934NR, Idsegahuizum', 'info25@warnerbros/eyeworks.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (26, 'Dachgelder & van Bentheim', 'Morrisboulevard 0, 4508NW, Zandberg', 'info26@dachgelder&vanbentheim.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (27, 'Koninklijke Schiffer', 'Lisannering 2, 4742 NV, Zuidveen', 'info27@koninklijkeschiffer.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (28, 'Eijkelboom NV', 'Willemboulevard 240, 4101LU, Warfstermolen', 'info28@eijkelboomnv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (29, 'Aarden & Bartels', 'Dirkstraat 339, 7638 ZK, Doldersum', 'info29@aarden&bartels.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (30, 'Pathé Bioscopen', 'Lindseydreef 1, 3687IP, Nieuwkuijk', 'info30@pathébioscopen.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (31, 'Suit Supply Topco', 'Juuldreef 137, 3472AF, Ruinen', 'info31@suitsupplytopco.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (32, 'Pauwels NV', 'Tiesboulevard 713, 5283YL, Nootdorp', 'info32@pauwelsnv.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (33, 'van de Wal Groep', 'Daanbaan 978, 9073YP, Beerta', 'info33@vandewalgroep.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (34, 'Mathieu Groep', 'Kyrabaan 2, 1560PZ, Biddinghuizen', 'info34@mathieugroep.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (35, 'Equens', 'Justinbaan 000, 2419 NT, Winkel', 'info35@equens.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (36, 'Royal Helmerhorst', 'Louiseboulevard 696, 2576 OF, Zandpol', 'info36@royalhelmerhorst.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (37, 'Kruns & Pons', 'Bentheboulevard 464, 5383XT, Druten', 'info37@kruns&pons.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (38, 'Symons BV', 'Esilaweg 4, 6758 XN, Wateringen', 'info38@symonsbv.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (39, 'Dow Benelux', 'Jonasweg 9, 5622 DK, Gasselte', 'info39@dowbenelux.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (40, 'Koninklijke van Dagsburg', 'Nikkisteeg 505, 6304SC, Nederweert-Eind', 'info40@koninklijkevandagsburg.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (41, 'Accenture', 'Wesselsteeg 5, 1437EC, Esch', 'info41@accenture.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (42, 'Stuivenberg & Scardino', 'Sennaweg 14, 5238 KC, Afferden L', 'info42@stuivenberg&scardino.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (43, 'Thomas NV', 'Veerledreef 300, 4064 LQ, Heide', 'info43@thomasnv.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (44, 'Royal Bakker', 'Sarahpad 8, 9310 BQ, Kûbaard', 'info44@royalbakker.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (45, 'Koninklijke Heerkens', 'Semhof 1, 9269 BT, Langerak', 'info45@koninklijkeheerkens.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (46, 'Lekkerland', 'Laurendreef 215, 1991 FL, Leersum', 'info46@lekkerland.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (47, 'van Doorn & van Breugel', 'Naomipad 32, 1577 SJ, Herwijnen', 'info47@vandoorn&vanbreugel.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (48, 'Royal Wildschut', 'Jasmijnboulevard 456, 6102QO, Belt-Schutsloot', 'info48@royalwildschut.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (49, 'Mathol NV', 'Rosasteeg 09, 6640 DU, Maarssen', 'info49@matholnv.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (50, 'Willems van Lier Groep', 'Kyanodreef 057, 2130RO, Sint Jansteen', 'info50@willemsvanliergroep.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (51, 'Royal Strik', 'Hannastraat 69, 4886CV, Roodeschool', 'info51@royalstrik.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (52, 'Stichting Zijlmans', 'Ayoubhof 713, 6151QJ, Aalten', 'info52@stichtingzijlmans.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (53, 'Aschman NV', 'Ninaweg 7, 6354 BK, Reutum', 'info53@aschmannv.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (54, 'Scharroo NV', 'Emmasteeg 0, 1065 OZ, Balloo', 'info54@scharroonv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (55, 'Brugman & Beekman', 'Marebaan 51, 2027NM, Bourtange', 'info55@brugman&beekman.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (56, 'KLM', 'Sarahstraat 203, 2384 YC, Molenhoek', 'info56@klm.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (57, 'Scardino & Cornelisse', 'Aiméehof 757, 4778EK, Kapellebrug', 'info57@scardino&cornelisse.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (58, 'Nyrstar holding', 'Isissingel 16, 7724BX, ''s-Heer Abtskerke', 'info58@nyrstarholding.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (59, 'van de Greef NV', 'Larslaan 434, 3780HJ, Margraten', 'info59@vandegreefnv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (60, 'Kas & van Bernicia', 'Annesingel 46, 3098 MS, Gaastmeer', 'info60@kas&vanbernicia.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (61, 'Verheij & Diesbergen', 'Mehmetdreef 4, 7799 GF, Goënga', 'info61@verheij&diesbergen.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (62, 'Vegt NV', 'Elizapad 06, 5869LT, Opende', 'info62@vegtnv.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (63, 'Alphabet Nederland', 'Madssingel 4, 9634 QS, De Punt', 'info63@alphabetnederland.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (64, 'Mercks & Strijker', 'Wesleystraat 05, 8838 VB, Zandhuizen', 'info64@mercks&strijker.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (65, 'Relx', 'Mariadreef 319, 6818UL, Idaerd', 'info65@relx.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (66, 'Broeders BV', 'Thijmenboulevard 9, 5195 FQ, Burgerbrug', 'info66@broedersbv.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (67, 'van Kuijc BV', 'Liekeweg 303, 4301FC, Oude Willem', 'info67@vankuijcbv.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (68, 'van Salmen NV', 'Fatimastraat 79, 4621KE, Abbenes', 'info68@vansalmennv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (69, 'Royal Corstiaens', 'Tijsdreef 67, 2858FI, Sommelsdijk', 'info69@royalcorstiaens.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (70, 'Kriens BV', 'Damianweg 1, 6350RW, Overasselt', 'info70@kriensbv.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (71, 'Godfrey van Alemannië Groep', 'Nielslaan 9, 6021 OK, Lutjegast', 'info71@godfreyvanalemanniëgroep.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (72, 'Janse Groep', 'Aidenring 0, 6462YY, Herveld', 'info72@jansegroep.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (73, 'Koninklijke van Venrooy', 'Roospad 8, 5278FT, Kreileroord', 'info73@koninklijkevanvenrooy.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (74, 'Sita', 'Emirstraat 0, 5389YZ, Achterveld', 'info74@sita.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (75, 'Wensen Groep', 'Aydensteeg 0, 5366 LK, Bunde', 'info75@wensengroep.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (76, 'Ghoerle & Smeets', 'Mustafahof 4, 5214 DP, Den Ilp', 'info76@ghoerle&smeets.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (77, 'Koninklijke van Kuijc', 'Lukasstraat 08, 4148QU, Stiens', 'info77@koninklijkevankuijc.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (78, 'Brouwer & Karels', 'Nathanhof 835, 1958TZ, Loenen', 'info78@brouwer&karels.nl', 'Logistiek');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (79, 'Veenendaal Groep', 'Elenabaan 61, 8925 PM, Hoogeloon', 'info79@veenendaalgroep.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (80, 'Ernst NV', 'Renspad 19, 3370EN, Vlissingen', 'info80@ernstnv.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (81, 'van Hemert BV', 'Emirstraat 0, 6520MD, Bruinehaar', 'info81@vanhemertbv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (82, 'Croon Elektrotechniek', 'Davepad 0, 2300 AC, Schiermonnikoog', 'info82@croonelektrotechniek.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (83, 'Koninklijke van Grondelle', 'Arielaan 696, 9972JG, Broeksterwâld', 'info83@koninklijkevangrondelle.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (84, 'Kirpenstein & Blaak', 'Mohamedsingel 380, 1702 DH, Elkenrade', 'info84@kirpenstein&blaak.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (85, 'van Boulogne BV', 'Juulsingel 4, 9624 ZZ, ''t Zand', 'info85@vanboulognebv.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (86, 'Hak & van Engeland', 'Juliusdreef 4, 4197XO, Windraak', 'info86@hak&vanengeland.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (87, 'Koninklijke van der Maath', 'Felixdreef 85, 7541 VF, Schoonebeek', 'info87@koninklijkevandermaath.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (88, 'Aebi Schmidt Nederland', 'Mickstraat 8, 5926 HN, Burgum', 'info88@aebischmidtnederland.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (89, 'Jeggij NV', 'Romylaan 82, 3524 FZ, Borne', 'info89@jeggijnv.nl', 'Bouw');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (90, 'de Wit & van Waas', 'Améliesingel 262, 8717 PU, Lichtenvoorde', 'info90@dewit&vanwaas.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (91, 'van Mook NV', 'Naudlaan 20, 1879XV, Pesse', 'info91@vanmooknv.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (92, 'Gruijl BV', 'Valeriering 8, 8737IU, Wissenkerke', 'info92@gruijlbv.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (93, 'Stoffelsz & Meis', 'Dionstraat 5, 6442UH, Hoogeveen', 'info93@stoffelsz&meis.nl', 'Onderwijs');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (94, 'van Bovene & de Keijser', 'Norahlaan 74, 1772CM, Oosterend', 'info94@vanbovene&dekeijser.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (95, 'Boddaugh BV', 'Yfkedreef 0, 5671 ZG, Oud Gastel', 'info95@boddaughbv.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (96, 'Exact', 'Lolastraat 821, 4324HS, Geerdijk', 'info96@exact.nl', 'Zorg');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (97, 'RTL Nederland', 'Jenssteeg 9, 8231JT, Schoonrewoerd', 'info97@rtlnederland.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (98, 'van Ooste BV', 'Ricksteeg 6, 7113JL, Wytgaard', 'info98@vanoostebv.nl', 'ICT');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (99, 'Ordina', 'Teunsteeg 41, 4948 GQ, Haarlemmerliede', 'info99@ordina.nl', 'Duurzaamheid');
INSERT INTO bedrijven (id, naam, adres, email, sector) VALUES (100, 'van der Velden & Groote', 'Norabaan 125, 7332GN, Eethen', 'info100@vandervelden&groote.nl', 'Zorg');
